CREATE TABLE app_user (
                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                     username VARCHAR(255) NOT NULL UNIQUE,
                     password VARCHAR(255) NOT NULL,
                     role VARCHAR(255) NOT NULL,
                     CONSTRAINT pk_app_user PRIMARY KEY (id)
);