api:
  baseUrl: http://localhost:8080/apiServer
  endpoints:
    computers: /computers
    gpus: /gpus
    rams: /rams
server:
  port: 80
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
