CREATE TABLE computer (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                          name VARCHAR(255) NOT NULL UNIQUE,
                          type VARCHAR(255) NOT NULL,
                          enclosure_name VARCHAR(255) NOT NULL,
                          cpu_name VARCHAR(255) NOT NULL,
                          ram_id BIGINT NOT NULL,
                          hard_disk_capacity INT NOT NULL,
                          gpu_id BIGINT NOT NULL,
                          power_supply INT NOT NULL,
                          price INT NOT NULL,
                          CONSTRAINT pk_computer PRIMARY KEY (id)
);

CREATE TABLE gpu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL UNIQUE,
    v_ram_capacity INT NOT NULL,
    CONSTRAINT pk_gpu PRIMARY KEY (id)
);

CREATE TABLE ram (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL UNIQUE,
    ram_capacity INT NOT NULL,
    memory_rate INT NOT NULL,
    CONSTRAINT pk_ram PRIMARY KEY (id)
);

ALTER TABLE computer
    ADD CONSTRAINT fk_computer_on_ram FOREIGN KEY (ram_id) REFERENCES ram (id);

ALTER TABLE computer
    ADD CONSTRAINT fk_computer_on_gpu FOREIGN KEY (gpu_id) REFERENCES gpu (id);

